stages:
  get_data:
    cmd: python src/stage_01_get_data.py --config=configs/config.yaml --credentials=configs/credentials.yaml
    deps:
      - src/stage_01_get_data.py
      - src/utils/common.py
      - configs/config.yaml
      - configs/credentials.yaml
    outs:
      - data/extracted_data/products.csv
  preprocessing_data:
    cmd: python src/stage_02_preprocessing.py --config=configs/config.yaml
    deps:
      - src/stage_02_preprocessing.py
      - src/DictionaryUtils/company_tags.txt
      - configs/config.yaml
      - src/DictionaryUtils/english_profanity_google.txt

  feature_engineering:
    cmd: python src/stage_03_feature_engineering.py --config=configs/config.yaml
    deps:
      - src/stage_03_feature_engineering.py
      - src/DictionaryUtils/service_tagger.txt
      - configs/config.yaml
  model_training:
    cmd: python src/stage_04_model_training.py --config=configs/config.yaml  --params=params.yaml
    deps:
      - src/stage_04_model_training.py
      - configs/config.yaml
      - params.yaml
      - data/feature_processed/feature.csv
    outs:
      - report/params.json
      - report/scores.json
