bucketname : dheeraj-2
filename : train.csv

source_download_dir:
  data_dir: data
  data_extract: extracted_data
  data_file: products.csv

preprocessed:
  data_dir: data
  data_processed: processed_data
  data_file: processed.csv

featured:
  feature_dir: data
  feature_processed: feature_processed
  feature_file: feature.csv
  rank_file: rank.csv
report:
  params: report/params.json
  scores: report/scores.json
model:
  dir: models
  file_name: random_forest.joblib

